#!/bin/bash

sudo hciconfig hci0 up
sudo hciconfig hci0 leadv 3
sudo hciconfig noscan
UUID="E2 0A 39 F4 73 F5 4B C4 A1 2F 17 D1 AD 07 A9 61"
MAJOR="00 00"
MINOR="00 00"
POWER="C8"
sudo hcitool -i hci0 cmd 0x08 0x0008 1E 02 01 1A 1A FF 4C 00 02 15 $UUID $MAJOR $MINOR $POWER 00


